# Generated by Django 5.0.1 on 2024-01-31 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTracker',
            fields=[
                ('jobNumber', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=50)),
                ('des', models.TextField()),
                ('qty', models.CharField(max_length=5)),
                ('dueDate', models.DateField()),
                ('shippingThisMonth', models.BooleanField(blank=True, null=True)),
                ('TA', models.CharField(max_length=5)),
                ('notes1', models.TextField(blank=True, null=True)),
                ('incomingInspection', models.BooleanField(blank=True, null=True)),
                ('ME', models.CharField(blank=True, max_length=2, null=True)),
                ('rush', models.BooleanField(blank=True, null=True)),
                ('notes2', models.TextField(blank=True, null=True)),
                ('estimatedHours', models.FloatField()),
                ('completedHours', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workCenter', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('estimatedHours', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=15)),
                ('stepNumber', models.IntegerField()),
                ('customNotes', models.TextField(blank=True, null=True)),
                ('jobNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worderTracker.workordertracker')),
            ],
        ),
    ]
