# Generated by Django 5.0.1 on 2024-01-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTracker',
            fields=[
                ('jobNumber', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dueDate', models.DateField()),
                ('incomingInspection', models.BooleanField()),
                ('notes', models.TextField()),
                ('ME', models.CharField(max_length=2)),
                ('rush', models.BooleanField()),
                ('completed', models.FloatField()),
                ('dateCompleted', models.DateField()),
            ],
        ),
    ]
