# Generated by Django 5.0.1 on 2024-01-29 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worderTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordertracker',
            name='ME',
        ),
        migrations.RemoveField(
            model_name='workordertracker',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='workordertracker',
            name='dateCompleted',
        ),
        migrations.RemoveField(
            model_name='workordertracker',
            name='incomingInspection',
        ),
        migrations.RemoveField(
            model_name='workordertracker',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='workordertracker',
            name='rush',
        ),
    ]
