# Generated by Django 5.0.1 on 2024-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worderTracker', '0002_jobnotes_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mes',
            name='id',
        ),
        migrations.AlterField(
            model_name='mes',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
