# Generated by Django 5.0.1 on 2024-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worderTracker', '0002_remove_workordertracker_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertracker',
            name='ME',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='workordertracker',
            name='incomingInspection',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordertracker',
            name='notes1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordertracker',
            name='notes2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordertracker',
            name='rush',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
