# Generated by Django 5.0.1 on 2024-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worderTracker', '0003_remove_mes_id_alter_mes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertracker',
            name='onHold',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='workordertracker',
            name='ops',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
