# Generated by Django 5.0.1 on 2024-03-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worderTracker', '0004_workordertracker_onhold_workordertracker_ops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineCode', models.CharField(max_length=20)),
                ('machineName', models.CharField(max_length=100)),
            ],
        ),
    ]
